function fig = OPIEpicture()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load OPIEpicture

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
   'Colormap',mat0, ...
   'MenuBar','none',...
	'Name','OPIE Picture', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[374.25 270 174.75 113.25], ...
	'Tag','Fig2');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontName','Ariel', ...
	'FontSize',28, ...
	'FontWeight','bold', ...
	'ForegroundColor',[0 0 1], ...
	'ListboxTop',0, ...
	'Position',[47 96 137 43], ...
	'String','O P I E', ...
	'Style','text', ...
	'Tag','StaticText1', ...
	'TooltipString','Optical Positioning Instrumentation and Evaluation');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontName','Ariel', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[6 37.5 67.5 25.5], ...
	'String','Path and File Name', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Ariel', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[84.75 45.75 82.5 17.25], ...
	'String','graph1', ...
	'Style','edit', ...
	'Tag','FileName');
h1 = uicontrol('Parent',h0, ...
   'CreateFcn','set(gcbo,''Value'',1);',...
   'Callback',['if get(gcbo,''Value'')==1,'...
      'set(findobj(''String'',''JPEG''),''Value'',0);'...
      'else,set(findobj(''String'',''JPEG''),''Value'',1);end;'],...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontName','Ariel', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[12 10.5 37.5 19.5], ...
	'String','BMP', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton1');
h1 = uicontrol('Parent',h0, ...
   'Callback',['if get(gcbo,''Value'')==1,'...
      'set(findobj(''String'',''BMP''),''Value'',0);'...
      'else,set(findobj(''String'',''BMP''),''Value'',1);end;'],...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontName','Ariel', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[60 10.5 39.75 21], ...
	'String','JPEG', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton2');
h1 = uicontrol('Parent',h0, ...
   'Callback',[''...
      'SaveString=get(findobj(''Tag'',''FileName''),''String'');'...
      'if get(findobj(''String'',''BMP''),''Value'')==1,Format=''bmp '';end;'...
      'if get(findobj(''String'',''JPEG''),''Value'')==1,Format=''jpeg'';end;'...
	   'close(''OPIE Picture'');'...
      'figure(2);'...
      'if PlotType == ''Trajectory'','...
      	'cla;reset(gca);'...
   	   'hold on;'...
   	   'plot(x(:,1)*XCal,y(:,1)*YCal,''b'',x(:,2)*XCal,y(:,2)*YCal,''r'');'...
   	   'axis([0,PicWidth*XCal,0,PicHeight*YCal]);'...
         'xlabel(''Trajectory'');'...
         'if get(findobj(''Tag'',''VelocityVector''),''Value'')==1,'...
         	'quiver(x(1:length(x)-1,1)*XCal,y(1:length(y)-1,1)*YCal,Vx(2:length(Vx),1),Vy(2:length(Vy),1),''g'');'...
            'quiver(x(1:length(x)-1,2)*XCal,y(1:length(y)-1,2)*YCal,Vx(2:length(Vx),2),Vy(2:length(Vy),2),''g'');'...
            'end;'...
         'if get(findobj(''Tag'',''AccelerationVector''),''Value'')==1,'...
         	'quiver(x(1:length(x)-1,1)*XCal,y(1:length(y)-1,1)*YCal,Ax(2:length(Ax),1),Ay(2:length(Ay),1),''m'');'...
            'quiver(x(1:length(x)-1,2)*XCal,y(1:length(y)-1,2)*YCal,Ax(2:length(Ax),2),Ay(2:length(Ay),2),''m'');'...
            'end;'...
         'end;'...
      'if PlotType == ''TimeSeries'','...
         'cla;reset(gca);'...
         'hold on;'...
         'if get(findobj(''Tag'',''X1''),''Value'')==1,plot(Time,X(:,1),''b-'');end;'...   
         'if get(findobj(''Tag'',''X2''),''Value'')==1,plot(Time,X(:,2),''b--'');end;'...
         'if get(findobj(''Tag'',''Y1''),''Value'')==1,plot(Time,Y(:,1),''r-'');end;'...
         'if get(findobj(''Tag'',''Y2''),''Value'')==1,plot(Time,Y(:,2),''r--'');end;'...
         'if get(findobj(''Tag'',''Vx1''),''Value'')==1,plot(Time,Vx(:,1),''c-'');end;'...
         'if get(findobj(''Tag'',''Vx2''),''Value'')==1,plot(Time,Vx(:,2),''c--'');end;'...
         'if get(findobj(''Tag'',''Vy1''),''Value'')==1,plot(Time,Vy(:,1),''m-'');end;'...
         'if get(findobj(''Tag'',''Vy2''),''Value'')==1,plot(Time,Vy(:,2),''m--'');end;'...
         'if get(findobj(''Tag'',''Ax1''),''Value'')==1,plot(Time,Ax(:,1),''g-'');end;'...
         'if get(findobj(''Tag'',''Ax2''),''Value'')==1,plot(Time,Ax(:,2),''g--'');end;'...
         'if get(findobj(''Tag'',''Ay1''),''Value'')==1,plot(Time,Ay(:,1),''k-'');end;'...
         'if get(findobj(''Tag'',''Ay2''),''Value'')==1,plot(Time,Ay(:,2),''k--'');end;'...
         'if get(findobj(''Tag'',''Theta''),''Value'')==1,plot(Time,Theta,''b:'');end;'...
         'if get(findobj(''Tag'',''Omega''),''Value'')==1,plot(Time,Omega,''r:'');end;'...
         'if get(findobj(''Tag'',''Alpha''),''Value'')==1,plot(Time,Alpha,''m:'');end;'...
      	'xlabel(''Time (sec)'');'...
      	'end;'...
      ''...
      'hold off;'...
      'if Format==''bmp '','...
      	'eval([''print -f2 -dbmp16m '' SaveString ''.bmp'']);'...
      'elseif Format==''jpeg'','...
         'eval([''print -f2 -djpeg100 '' SaveString ''.jpg'']);'...
         'end;'...
      'close(2);'...
   	''],...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[129 8.25 31.5 25.5], ...
	'String','OK', ...
	'Tag','Pushbutton1');
if nargout > 0, fig = h0; end
