function fig = OPIEsave()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load OPIEsave

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
   'Colormap',mat0, ...
   'MenuBar','none',...
	'Name','OPIE Save', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[173.25 344.25 228.75 186], ...
	'Tag','Fig2');
h1 = uicontrol('Parent',h0, ...
   'Callback',[''...
      'if get(findobj(''String'',''MATLAB''),''Value'')==1,'...
      	'save(get(findobj(''Tag'',''SaveFile''),''String''),''Time'',''X'',''Y'''...
         ',''Vx'',''Vy'',''Ax'',''Ay'',''Theta'',''Omega'',''Alpha'',''VideoPath'''...
         ',''FileName'',''CalibrationFile'',''EquilFile'',''StartFrame'',''EndFrame'''...
         ',''SampleRate'',''Diameter'',''PicWidth'',''PicHeight'',''ROIScaleFactor'''...
         ',''XRef'',''YRef'',''XCal'',''YCal'');'...
      'elseif get(findobj(''String'',''Excel''),''Value'')==1,'...
      	'fid=fopen(get(findobj(''Tag'',''SaveFile''),''String''),''w'');'...
         'fprintf(fid,''OPIE OUTPUT FILE\n\n'');'...
         'fprintf(fid,''Video Files:\t%s%s\n'',VideoPath,FileName);'...
         'fprintf(fid,''Start Frame:\t%f\n'',StartFrame);'...
         'fprintf(fid,''End Frame:\t%f\n'',EndFrame);'...
         'fprintf(fid,''Sampling Rate:(Frames/s)\t%f\n'',SampleRate);'...
         'fprintf(fid,''Picture Height:(Pix)\t%f\n'',PicHeight);'...
         'fprintf(fid,''Picture Width:(Pix)\t%f\n'',PicWidth);'...
         'fprintf(fid,''ROI Scale Factor:\t%f\n'',ROIScaleFactor);'...
         'fprintf(fid,''Calibration File:\t%s%s\n'',VideoPath,CalibrationFile);'...
         'fprintf(fid,''Circle Diameter:(Length)\t%f\n'',Diameter);'...
         'fprintf(fid,''X Calibration:(Length/Pix)\t%f\n'',XCal);'...
         'fprintf(fid,''Y Calibration:(Length/Pix)\t%f\n'',YCal);'...
         'fprintf(fid,''EquilibriumFile:\t%s%s\n'',VideoPath,EquilFile);'...
         'fprintf(fid,''Equilibrium (X1,Y1):(Pix)\t%f\t%f\n'',XRef(1),YRef(1));'...
			'fprintf(fid,''Equilibrium (X2,Y2):(Pix)\t%f\t%f\n'',XRef(2),YRef(2));'...
         'fprintf(fid,''\n\n'');'...
         'fprintf(fid,''Time\tX 1\tY 1\tX 2\tY 2\tVx 1\tVy 1\tVx 2\tVy 2\tAx 1\tAy 1\tAx 2\tAy 2\t'...
         	'Theta\tOmega\tAlpha\tTrajectory X1\tTrajectory Y1\tTrajectory X2\tTrajectory Y2\n'');'...
         'fprintf(fid,''(s)\t(Length)\t(Length)\t(Length)\t(Length)\t(Length/s)\t(Length/s)\t(Length/s)\t(Length/s)'...
         	'\t(Length/s^2)\t(Length/s^2)\t(Length/s^2)\t(Length/s^2)\t(Deg)\t(Deg/s)\t(Deg/s^2)'...
         	'\t(Length)\t(Length)\t(Length)\t(Length)\n'');'...
         'for i=1:length(X),'...
         	'fprintf(fid,''%f\t%f\t%f\t%f\t%f\t'',Time(i),X(i,1),Y(i,1),X(i,2),Y(i,2));'...
            'fprintf(fid,''%f\t%f\t%f\t%f\t'',Vx(i,1),Vy(i,1),Vx(i,2),Vy(i,2));'...
            'fprintf(fid,''%f\t%f\t%f\t%f\t'',Ax(i,1),Ay(i,1),Ax(i,2),Ay(i,2));'...
            'fprintf(fid,''%f\t%f\t%f\t'',Theta(i,1),Omega(i),Alpha(i));'...
            'fprintf(fid,''%f\t%f\t%f\t%f\n'',x(i,1)*XCal,y(i,1)*YCal,x(i,2)*XCal,y(i,2)*YCal);'...
            'end;'...
         'fclose(fid);'...
         'end;'...
         ],...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[112.5 35.25 54 23.25], ...
	'String','Save', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','close(gcf);OPIEgrapher;', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[14.25 35.25 60.75 23.25], ...
	'String','Back', ...
	'Tag','Pushbutton2', ...
	'TooltipString','Return to the grapher.');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','close(gcf);clear;', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',mat2, ...
	'String','Quit', ...
	'Tag','Pushbutton1', ...
	'TooltipString','Exit OPIE and Clear Workspace');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontName','Ariel', ...
	'FontSize',28, ...
	'FontWeight','bold', ...
	'ForegroundColor',[0 0 1], ...
	'ListboxTop',0, ...
	'Position',[0.2754098360655738 0.814516129032258 0.4491803278688525 0.1733870967741935], ...
	'String','O P I E', ...
	'Style','text', ...
	'Tag','StaticText1', ...
	'TooltipString','Optical Positioning Instrumentation and Evaluation');
h1 = uicontrol('Parent',h0, ...
   'Callback','close(gcf);OPIEinfo;',...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[112.5 5.25 99.75 24.75], ...
	'String','New Analysis', ...
	'Tag','Pushbutton3', ...
	'TooltipString','Begin a new analysis.');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontName','Ariel', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[9 123.75 104.25 15.75], ...
	'String','Path and File Name:', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
   'CreateFcn','set(gcbo,''String'',VideoPath)',...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Ariel', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[112.5 123 107.25 17.25], ...
	'String','', ...
	'Style','edit', ...
	'Tag','SaveFile');
h1 = uicontrol('Parent',h0, ...
   'CreateFcn','set(gcbo,''Value'',1);',...
   'Callback',['if get(gcbo,''Value'')==1,'...
   	'set(findobj(''String'',''Excel''),''Value'',0);end;'],...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontName','Ariel', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[69 91.5 103.5 19.5], ...
	'String','MATLAB', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton1');
h1 = uicontrol('Parent',h0, ...
   'Callback',['if get(gcbo,''Value'')==1,'...
   	'set(findobj(''String'',''MATLAB''),''Value'',0);end;'],...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontName','Ariel', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[68.25 67.5 104.25 20.25], ...
	'String','Excel', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton2');
if nargout > 0, fig = h0; end
