function fig = OPIEfirstframe()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load OPIEfirstframe

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
   'Colormap',mat0, ...
   'MenuBar','none',...
	'Name','OPIE First Frame', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[173.25 215.25 420 315], ...
	'Tag','Fig2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontName','Ariel', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[363 78 60 21], ...
	'String','Video On', ...
	'Style','checkbox', ...
	'Tag','VideoOn', ...
   'TooltipString','Turns the display of the video on or off during analysis.',...
   'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'Callback',['[x(1,2),y(1,2)]=ginput(1);x=round(x);y=round(y);'...
  	      	],...
	'FontName','Ariel', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[364.5 135 50.25 24], ...
	'String','Point 2', ...
	'Tag','Pushbutton4', ...
	'TooltipString','Choose the second target.');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'Callback',['[x(1,1),y(1,1)]=ginput(1);x=round(x);y=round(y);' ...
	      	],...
	'FontName','Ariel', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[364.5 170.25 50.25 24], ...
	'String','Point 1', ...
	'Tag','Pushbutton3', ...
	'TooltipString','Choose the first target.');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','close(gcf);clear;', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',mat6, ...
	'String','Quit', ...
	'Tag','Pushbutton1', ...
	'TooltipString','Exit OPIE and Clear Workspace');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','close(gcf);OPIEinfo;', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[228.75 6 76.5 23.25], ...
	'String','Back', ...
	'Tag','Pushbutton2', ...
	'TooltipString','Return to the information window.');
h1 = uicontrol('Parent',h0, ...
   'Callback',['VideoOn=get(findobj(''Tag'',''VideoOn''),''Value'');'...
      'close(gcf);'...
      'save c:\matlabr11\opie\DefaultData VideoPath FileName CalibrationFile EquilFile '...
      'StartFrame EndFrame SampleRate Diameter ROIScaleFactor XCal YCal XRef YRef x y;'...
      'ROI=ROIScaleFactor;'...
   	'[PicHeight,PicWidth]=size(A);'...
   	'PicWidth=PicWidth-11;'...
      'a=A(max(round(y(1,1)-(PicHeight/ROI)/2),0):min(round(y(1,1)+(PicHeight/ROI)/2),PicHeight),'...
      	'max(round(x(1,1)-(PicWidth/ROI)/2),0):min(round(x(1,1)+(PicWidth/ROI)/2),PicWidth));'...
      'b=A(max(round(y(1,2)-(PicHeight/ROI)/2),0):min(round(y(1,2)+(PicHeight/ROI)/2),PicHeight),'...
      	'max(round(x(1,2)-(PicWidth/ROI)/2),0):min(round(x(1,2)+(PicWidth/ROI)/2),PicWidth));'...
      '[x,y,PicHeight,PicWidth]=OPIEAlgorithm2(VideoPath,FileName,StartFrame,EndFrame,SampleRate,'...
      'ROIScaleFactor,XCal,YCal,XRef,YRef,VideoOn,x,y,a,b);'...
      '[x,y,X,Y,Vx,Vy,Ax,Ay,Theta,Omega,Alpha,Time]=OPIEextrapolate(x,y,XCal,YCal,XRef,YRef,SampleRate,PicHeight);'...
      'OPIEgrapher;'
   	''],...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[329.25 6 76.5 23.25], ...
	'String','Continue', ...
	'Tag','Pushbutton2', ...
	'TooltipString','Begin the analysis.');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontName','Ariel', ...
	'FontSize',28, ...
	'FontWeight','bold', ...
	'ForegroundColor',[0 0 1], ...
	'ListboxTop',0, ...
	'Position',[0.3 0.8976190476190477 0.3821428571428571 0.1], ...
	'String','O P I E', ...
	'Style','text', ...
	'Tag','StaticText1', ...
	'TooltipString','Optical Positioning Instrumentation and Evaluation');
h1 = axes('Parent',h0, ...
   'CreateFcn',['if StartFrame >= 1 & StartFrame < 10,'...
      'A=imread([VideoPath,FileName,''000'',num2str(StartFrame),''.bmp'']);'...
      'elseif StartFrame >= 10 & StartFrame < 100,'...
      'A=imread([VideoPath,FileName,''00'',num2str(StartFrame),''.bmp'']);'...
      'elseif StartFrame >= 100 & StartFrame < 1000,'...
      'A=imread([VideoPath,FileName,''0'',num2str(StartFrame),''.bmp'']);'...
      'elseif StartFrame >= 1000,'...
      'A=imread([VideoPath,FileName,num2str(StartFrame),''.bmp'']);'...
      'end;'...
   	'imshow(A);zoom on;'],...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat8, ...
	'Position',[20 49 460 325], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4989106753812636 -0.07407407407407418 9.160254037844386], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.06318082788671024 0.4969135802469135 9.160254037844386], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.04357298474945534 1.141975308641975 9.160254037844386], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4989106753812636 1.021604938271605 9.160254037844386], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
if nargout > 0, fig = h0; end
