function fig = OPIEcalibration()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load OPIEcalibration

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
   'Colormap',mat0, ...
   'MenuBar','none',...
	'Name','OPIE Calibration', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[173.25 215.25 420 315], ...
	'Tag','Fig1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontName','Ariel', ...
	'FontSize',28, ...
	'FontWeight','bold', ...
	'ForegroundColor',[0 0 1], ...
	'ListboxTop',0, ...
	'Position',[0.3 0.8928571428571429 0.3821428571428572 0.1], ...
	'String','O P I E', ...
	'Style','text', ...
	'Tag','StaticText1', ...
	'TooltipString','Optical Positioning Instrumentation and Evaluation');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','close(gcf);clear;', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',mat2, ...
	'String','Quit', ...
	'Tag','Pushbutton1', ...
   'TooltipString','Exit OPIE and Clear Workspace');
h1 = uicontrol('Parent',h0, ...
   'Callback','close(gcf);OPIEinfo;',...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[229.25 5.25 76.5 23.25], ...
	'String','Back', ...
	'Tag','Pushbutton2', ...
	'TooltipString','Return to the information window.');
h1 = uicontrol('Parent',h0, ...
   'Callback',['close(gcf);'...
      'save c:\matlab\opie\DefaultData VideoPath FileName CalibrationFile EquilFile '...
      'StartFrame EndFrame SampleRate Diameter ROIScaleFactor XCal YCal XRef YRef x y;'...
      'OPIEequilibrium;'],...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[329.25 5.25 76.5 23.25], ...
	'String','Continue', ...
	'Tag','Pushbutton2', ...
	'TooltipString','Save this calibration and choose reference locations for each target.');
h1 = uicontrol('Parent',h0, ...
   'Callback','[x,y]=ginput(2);XCal=abs(Diameter/(round(x(1))-round(x(2))));',...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[355 186.75 60 24], ...
	'String','Horizontal', ...
	'Tag','Pushbutton3', ...
	'TooltipString','Choose the left and right edges of the calibration circle.');
h1 = uicontrol('Parent',h0, ...
   'Callback','[x,y]=ginput(2);YCal=abs(Diameter/(round(y(1))-round(y(2))));',...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[355 153 60 24], ...
	'String','Vertical', ...
	'Tag','Pushbutton4', ...
	'TooltipString','Choose the top and bottom edges of the calibration circle.');
h1 = axes('Parent',h0, ...
   'CreateFcn','A=imread([VideoPath,CalibrationFile,''0001.bmp'']);imshow(A);zoom on;',...
	'Units','pixels', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat3, ...
	'Position',[13 45 453 328], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.497787610619469 -0.07339449541284404 9.160254037844386], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.06415929203539823 0.4954128440366972 9.160254037844386], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.02876106194690266 1.143730886850153 9.160254037844386], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.497787610619469 1.021406727828746 9.160254037844386], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
if nargout > 0, fig = h0; end
