function fig = VIDEO()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load VIDEO

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'Name','UNH OE Video Processing Toolbox', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[173.25 215.25 420 315], ...
	'Tag','Fig1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontName','Ariel', ...
	'FontSize',24, ...
	'FontWeight','bold', ...
	'ForegroundColor',[0 0 0.627450980392157], ...
	'ListboxTop',0, ...
	'Position',[57 243.75 308.25 60.75], ...
	'String','UNH Ocean Engineering Video Processing Toolbox', ...
	'Style','text', ...
   'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
   'Callback','close(gcf);clear;',...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[29.25 12.75 54 23.25], ...
   'String','Quit', ...
   'TooltipString','Quit and clear the memory',...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','close(gcf);OPIE;', ...
	'FontName','Ariel', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[63.75 94.5 127.5 28.5], ...
   'String','OPIE Motion Tracking', ...
   'TooltipString','Begin a motion tracking analysis.',...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','close(gcf);', ...
	'FontName','Ariel', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[228 94.5 127.5 28.5], ...
   'String','Oil Slick Analysis', ...
   'TooltipString','Begin an Oil Slick Analysis (OSA).',...
   'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[85 61.5 85 28.5], ...
   'String','OPIE Grapher', ...
   'TooltipString','Review previously analyzed data using the OPIE Grapher.',...
	'Tag','Pushbutton3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontName','Ariel', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[250.75 60 85 28.5], ...
   'String','OSA Grapher', ...
   'TooltipString','Review previously analyzed data using the OSA Grapher.',...
	'Tag','Pushbutton4');
h1 = axes('Parent',h0, ...
	'Units','pixels', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'CLim',[0 255], ...
	'CLimMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat2, ...
	'DataAspectRatioMode','manual', ...
	'Layer','top', ...
	'Position',[286 170 220 140], ...
	'Tag','Axes1', ...
	'TickDir','out', ...
	'TickDirMode','manual', ...
	'Visible','off', ...
	'WarpToFill','off', ...
	'WarpToFillMode','manual', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 768.5], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 484.5], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);
h2 = image('Parent',h1, ...
	'BusyAction','cancel', ...
	'CData',mat3, ...
	'CDataMapping','scaled', ...
	'Interruptible','off', ...
	'Tag','Axes1Image1', ...
	'XData',[1 768], ...
	'YData',[1 484]);
h2 = text('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Interruptible','off', ...
	'Position',[382.746575342466 573.8972602739726 4539.445362085778], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Interruptible','off', ...
	'Position',[-118.7328767123288 247.7602739726027 4539.445362085778], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Interruptible','off', ...
	'Position',mat4, ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Interruptible','off', ...
	'Position',[382.746575342466 -25.77397260273978 4539.445362085778], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
h1 = axes('Parent',h0, ...
	'Units','pixels', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'CLim',[0 255], ...
	'CLimMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat5, ...
	'DataAspectRatioMode','manual', ...
	'Layer','top', ...
	'Position',[57 170 220 140], ...
	'Tag','Axes2', ...
	'TickDir','out', ...
	'TickDirMode','manual', ...
	'Visible','off', ...
	'WarpToFill','off', ...
	'WarpToFillMode','manual', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 768.5], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 484.5], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);
h2 = image('Parent',h1, ...
	'BusyAction','cancel', ...
	'CData',mat6, ...
	'CDataMapping','scaled', ...
	'Interruptible','off', ...
	'Tag','Axes2Image1', ...
	'XData',[1 768], ...
	'YData',[1 484]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[382.7465753424658 573.8972602739726 4539.445362085778], ...
	'Tag','Axes2Text4', ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat7, ...
	'Rotation',90, ...
	'Tag','Axes2Text3', ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-199.3904109589043 -386.9794520547947 4539.445362085778], ...
	'Tag','Axes2Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[382.7465753424658 -25.77397260273978 4539.445362085778], ...
	'Tag','Axes2Text1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
if nargout > 0, fig = h0; end
