a(1) = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
   'Name','Configuration', ...
   'Resize','Off', ...
	'NumberTitle','off', ...
   'Position',[193.75 175.75 204.75 200], ...
   'WindowStyle','modal', ...
	'Tag','Fig1');
uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[10 176.75 80 11.25], ...
   'String','Angle Alpha :', ...
   'HorizontalAlignment','left', ...
	'Style','text', ...
	'Tag','StaticText1');
a(2) = uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[75 175.25 25.5 14.25], ...
	'String','0', ...
	'Style','edit', ...
   'HorizontalAlignment','left', ...
   'Tag','EditText1');
uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[10 156.75 80 11.25], ...
   'String','Angle Beta :', ...
   'HorizontalAlignment','left', ...
	'Style','text', ...
	'Tag','StaticText3');
a(3) = uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[75 155.25 25.5 14.25], ...
   'HorizontalAlignment','left', ...
	'String','0', ...
	'Style','edit', ...
   'Tag','EditText3');
uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[5 126.75 80 11.25], ...
   'String','Calibration Diameter :', ...
   'HorizontalAlignment','left', ...
	'Style','text', ...
	'Tag','StaticText3');
a(4) = uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[95 125.25 25.5 14.25], ...
   'HorizontalAlignment','left', ...
	'String','4.45', ...
	'Style','edit', ...
   'Tag','EditText3');
uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[5 106.75 80 11.25], ...
   'String','Calibration Unit :', ...
   'HorizontalAlignment','left', ...
	'Style','text', ...
	'Tag','StaticText2');
a(5) = uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[95 105.25 25.5 14.25], ...
	'String','in', ...
   'HorizontalAlignment','left', ...
	'Style','edit', ...
   'Tag','EditText2');
uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[5 76.75 100 11.25], ...
   'String','X coordinate of the POI :', ...
   'HorizontalAlignment','left', ...
	'Style','text', ...
	'Tag','StaticText3');
a(6) = uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[115 75.25 25.5 14.25], ...
   'HorizontalAlignment','left', ...
	'String','0', ...
	'Style','edit', ...
   'Tag','EditText3');
uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[5 56.75 100 11.25], ...
   'HorizontalAlignment','left', ...
   'String','Y coordinate of the POI :', ...
	'Style','text', ...
	'Tag','StaticText4');
a(7) = uicontrol('Parent',a(1), ...
	'Units','points', ...
   'HorizontalAlignment','left', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[115 55.25 25.5 14.25], ...
	'String','0', ...
	'Style','edit', ...
   'Tag','EditText4');
uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
   'HorizontalAlignment','left', ...
	'Position',[5 36.75 100 11.25], ...
   'String','Z coordinate of the POI :', ...
	'Style','text', ...
	'Tag','StaticText5');
a(8) = uicontrol('Parent',a(1), ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
   'HorizontalAlignment','left', ...
	'Position',[115 35.25 25.5 14.25], ...
	'String','0', ...
	'Style','edit', ...
   'Tag','EditText5');

callbackstr = ['alpha = str2num(get(a(2),''string'')); '...
      'beta = str2num(get(a(3),''string'')); '...
      'calibration_diameter = str2num(get(a(4),''string'')); '...
      'calibration_units = get(a(5),''string''); '...
      'userpoint(1,1)  = str2num(get(a(6),''string'')); '...
      'userpoint(1,2)  = str2num(get(a(7),''string'')); '...
      'userpoint(1,3)  = str2num(get(a(8),''string'')); '...
      'close(a(1)); clear a;'];
uicontrol('Parent',a(1), ...
	'Units','points', ...
	'Callback',callbackstr, ...
	'Position',[72.75 10.5 60 18.75], ...
	'String','OK', ...
   'Tag','Pushbutton1');
