eval(['save ' input_file ' pth fname  frame_start frame_end' ...
' frames_per_sec ' ...
' dot1 dot2 dot3 area1 area2 area3' ...
' xareaC1 xareaC2 xareaC3 xareaD1 xareaD2 xareaD3']);
fprintf('The input file %s has been created.\n',input_file);