figure( ...
	'NumberTitle','off', ...
	'Name','Offshore Model Basin Non Contact Motion System', ...
	'Resize','off', ...
	'MenuBar','none');
mars = imread('mars1.jpg');
image (mars);
axis off;
clear mars;
set(gca,'position',[0 0 1 1]);
text(.22,.95,'Offshore Model Basin ','units','normalized','fontsize',24, ...
   'color','cyan');
text(.15,.80,'University of New Hampshire','units','normalized','fontsize',24, ...
   'color','cyan');
text(.08,.65,'Non Contact Motion Measuring System','units','normalized','fontsize',20, ...
   'color','cyan');
text(.03,.05,'Press Enter To Continue','units','normalized','fontsize',14, ...
   'color','cyan');
pause;
delete(gca);
set(gcf,'color',[.7 .7 .7]);
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.1 .801 .3 .075], ...
    'String','Calibration', ...
    'Callback','video_cal;');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.1 .725 .3 .074], ...
    'String','Create Input File', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.1 .649 .3 .074], ...
    'String','Process Zero Position', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.1 .573 .3 .074], ...
    'String','Compute Motions', ...
    'Callback','opie3d_c');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.1 .497 .3 .074], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.1 .421 .3 .074], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.1 .344 .3 .074], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.1 .268 .3 .074], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.1 .191 .3 .074], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.6 .801 .3.075], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.6 .725 .3.075], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.6 .649 .3.075], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.6 .573 .3.075], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.6 .497 .3.075], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.6 .421 .3.075], ...
    'String','', ...
    'Callback','');
uicontrol( ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[.2 .01 .6 .074], ...
    'String','Quit NCMMS', ...
    'Callback','close all;');
 