% Text that identifies program
txt = uicontrol(gcf,'Style','text','Position',[65 390 225 20],...
'String','Selection of the Two Equilibrium Points ','BackgroundColor',[0 0 0],...
'ForegroundColor',[1 1 1]);

frame_txt = uicontrol(gcf,'Style','text','Position',[375 390 130 25],...
'String','Currently Selecting From Frame:  ','BackgroundColor',[0 0 0],...
'ForegroundColor',[1 .8 1],'HorizontalAlignment','Left');

frame_txt2 = uicontrol(gcf,'Style','text','Position',[420 370 25 20],...
'String',ename,'BackgroundColor',[0 0 0],...
'ForegroundColor',[1 1 .8]);

efile=[path,ename,'.bmp'];
[A,map]=bmpread(efile);
imshow(A,map);

refresh=uicontrol(gcf,'Style','pushbutton','String',...
'Clear Points','Position',[55 35 115 25],'Callback',...
[',imshow(A,map),']);

quit=uicontrol(gcf,'Style','pushbutton','String',...
'Quit','Position',[55 5 115 25],'BackgroundColor',[.9 1 1],'Callback',...
['close(gcf)',',Return,']);

zm_on = uicontrol(gcf,'Style','checkbox','String','Zoom On',...
'Pos',[180 35 90 25],'Value',0,'BackgroundColor',[.701961 .701961 .701961],...
'CallBack',['set(zm_on,''Value'',1),','set(zm_off,''Value'',0),','imzoom on']);

zm_off = uicontrol(gcf,'Style','checkbox','String','Zoom Off',...
'Pos',[180 5 90 25],'Value',1,'BackgroundColor',[.701961 .701961 .701961],...
'CallBack',['set(zm_on,''Value'',0),',...
'set(zm_off,''Value'',1),','imzoom off']);

lft_pnt = uicontrol(gcf,'Style','pushbutton','String',...
'Select first point','Position',[280 35 120 25],'BackgroundColor',[.9 1 1],...
'Callback',['[xref(1),xref(2)]=ginput(1);',',imzoom out,','xref(1)=round(xref(1));','xref(2)=round(xref(2));']);

rt_pnt = uicontrol(gcf,'Style','pushbutton','String',...
'Select second point','Position',[280 5 120 25],'BackgroundColor',[.9 1 1],...
'Callback',['[xref(3),xref(4)]=ginput(1);',',imzoom out,','xref(3)=round(xref(3));','xref(4)=round(xref(4));']);


show_pnts=uicontrol(gcf,'Style','pushbutton','String',...
'Show points','Position',[410 35 115 25],'Callback',...
[',point,']);

finished=uicontrol(gcf,'Style','pushbutton','String',...
'Finished','Position',[410 5 115 25],'BackgroundColor',[.9 1 1],'Callback',...
['close(gcf),pick']);